### PR TITLE
Extend protocol view to show points for each trick

### PR DESCRIPTION
**Pull request by jmizv**
I've added another column to the protocol view showing the accumulated sum of points of both parties:

grafik

This column will be empty for Null-Spiel obviously. The numbers are bold if one party reaches 61 or 60 points, e.g. winning the game.

### CODE REVIEW

**Comment by rnauber** [comment]
Thank you! Should I do a release now?

**Comment by rnauber** [comment]
... or even better, you can release it yourself, if you want! I invited you to this repository, @jmizv! It is great to see the development is starting again!

**Comment by jmizv** [comment]
Thank you. I will take a look how to release it :)

**Comment by rnauber** [comment]
Great! It is really simple: 
1) you have to increase the version name and version here:
https://github.com/rnauber/xskat-android/blob/545190ddbfa9e204ef73df7bc932960411092390/app/build.gradle#L10

2) and then you have to tag that commit with an appropriate tag

3) F-Droid will automatically take care of the rest, although that may take a while...

**Pull request merged**
